# Generated by Django 3.0.5 on 2020-12-31 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContainer',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_type', models.CharField(max_length=255)),
                ('connected_container_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ProductContainer')),
            ],
        ),
    ]
