# Generated by Django 3.0.5 on 2020-12-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
