# Generated by Django 3.0.5 on 2020-12-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Stores'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='product_quantity',
            field=models.IntegerField(max_length=3),
        ),
    ]
