# Generated by Django 3.0.5 on 2020-12-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201211_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('store_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Stores')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_dis', models.TextField(max_length=400)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StoreInfo',
        ),
    ]
